### ISSUE TITLE
Revamp publishing of guides such as concise guides & scm guide

### ISSUE THREAD

**Issue by torgo** [ossf/wg-best-practices-os-developers#158]

**Comment by torgo** [comment]
As discussed in the call today - create a publishing process of some kind to publish these guides on openssf.org rather than in github directories.

**Comment by david-a-wheeler** [comment]
We now have https://bp.openssf.org working. The DNS is set up, TLS is working and enforced, and the pages in /docs are automatically regenerated whenever the markdown is merged into the main branch.

Here are some examples:

https://bp.openssf.org/Concise-Guide-for-Developing-More-Secure-Software.html
https://bp.openssf.org/Concise-Guide-for-Evaluating-Open-Source-Software.md

Do people like this direction? We need to change the CSS, see #160. Once we decide this approach is "ready to launch" we'll need to change sites to use these new URLs, see #161.

**Comment by david-a-wheeler** [comment]
> create a publishing process of some kind to publish these guides on openssf.org rather than in github directories.

Two quick clarifications:

1. We'll still *edit* these guides on GitHub. The change proposed here is to create a *publishing* process so that the "final pretty versions" will appear somewhere in a subdomain of openssf.org. If someone goes to GitHub to view the materials, they'll still see them.

2. There's a proposal to use a different subdomain other than "bp". Currently "best" seems to be leading, i.e., "best.openssf.org". If you have an opinion on the name, please comment here soon: https://github.com/ossf/wg-best-practices-os-developers/issues/162

**Comment by david-a-wheeler** [comment]
NB: The "bp.openssf.org" domain is not longer available. Stay tuned for the all-new "best.openssf.org" domain! See: https://github.com/ossf/wg-best-practices-os-developers/issues/162

**Comment by david-a-wheeler** [comment]
Note: The ".html" suffix will be *optional* (unless we change our configuration). So once best.openssf.org is working with TLS, we can use these links:

* https://best.openssf.org/Concise-Guide-for-Developing-More-Secure-Software
* https://best.openssf.org/Concise-Guide-for-Evaluating-Open-Source-Software

**Comment by david-a-wheeler** [comment]
We've now done this for the concuse guides. Now we can discuss if this is a template we should follow.
