### ISSUE TITLE
Compiler Hardening Guide: Missing Binutils version for `-rpath` and `--enable-new-dtags`

### ISSUE THREAD

**Issue by thomasnyman** [ossf/wg-best-practices-os-developers#164]
The `-Wl,-rpath` and `-Wl,--enable-new-dtags` options under *Discouraged Compiler Options* section are missing Binutils version information. The missing version information should be added for consistency.

**Comment by siddhesh** [comment]
As far as versions are concerned, `--enable-new-dtags` seems to have been available since at least 2000 (`binutils-2_11` seems to be the earliest tag in the repo) and `-rpath` appears in the ChangeLog in around 1994:

```
+Wed Jul 20 15:46:44 1994  Ian Lance Taylor  (ian@sanguine.cygnus.com)
+
+       * elfcode.h (NAME(bfd_elf,size_dynamic_sections)): Add rpath
+       argument.  If it is not NULL, use it to set DT_RPATH.
+       * bfd-in.h (bfd_elf32_size_dynamic_sections): Update prototype.
+       (bfd_elf64_size_dynamic_sections): Likewise.
+       * bfd-in2.h: Rebuilt.
```

They're old enough that maybe just putting in 2.11 is sufficient, what do you think?

Looking at the _Discouraged Compiler Options_ section a bit closer though, ISTM that the mention of `-Wl,--enable-new-dtags` option is unnecessary.  All it does is make the linker generate `DT_RUNPATH` instead of `DT_RPATH` when `-Wl,-rpath` is passed, it doesn't really do anything on its own.  Could we just drop it?
