### ISSUE TITLE
Compiler Hardening Guide should include -ftrivial-auto-var-init

### ISSUE THREAD

**Issue by thomasnyman** [ossf/wg-best-practices-os-developers#245]
Brought up during the [C/C++ Compiler BP Call 2023-09.27](https://docs.google.com/document/d/1UClGUnOSkOH_wab6Lx43KUdkaK37L8sbWJ_GPZvc1YY/edit#bookmark=id.863n4hp4nw9q).

The `-ftrivial-auto-var-init=[uninitialized|pattern|zero]` option will make the compiler initialize automatic variables with either a pattern or with zeroes (depending on the chosen option argument) to increase program security by preventing uninitialized memory disclosure and use.

This flag is supported since [GCC 12](https://gcc.gnu.org/gcc-12/changes.html) and [Clang 8.0](https://releases.llvm.org/8.0.0/tools/clang/docs/ReleaseNotes.html#major-new-features).

## Considerations and references
- [Patch and thread on GCC mailing list](https://gcc.gnu.org/pipermail/gcc-patches/2021-February/565514.html)
- [GCC Documentation](https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Optimize-Options.html#index-ftrivial-auto-var-init)
- [Thread in LLVM Phabricator](https://reviews.llvm.org/D54604?id=174471)
- [Potential performance regressions caused by `-ftrivial-auto-var-init`](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111523)
- [Endorsement from the Linux kernel community](https://lore.kernel.org/lkml/CAHk-=wgTM+cN7zyUZacGQDv3DuuoA4LORNPWgb1Y_Z1p4iedNQ@mail.gmail.com/)

**Comment by siddhesh** [comment]
See also: performance regression in systemd due to this option: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111523

**Comment by thesamesam** [comment]
There's nuance as to whether or not one should use `zero` or `pattern` as well:
* https://github.com/llvm/llvm-project/issues/44842
* https://inbox.sourceware.org/gcc-patches/8A3E5AA3-0785-4C2E-B75B-9388B703FFEA@gmail.com/T/#ma451313793180e6699a03d0f92ff11a1e08dd1b4

`zero` benefits from dead store elimination as well as not "looking valid" so it's possibly more likely it'll take some innocuous path rather than one which tries to operate on real data and write to disk or something.

But `pattern` is easier to spot in a backtrace or when it leaks into output.

**Comment by Ext3h** [comment]
And yet both `zero` and `pattern` have the major drawback that they will actually *prevent* external tools such as `valgrind` from being able to *detect* unsafe, uninitialized stack reads.

It's a gives a dangerous feeling of false safety, which results in less portable code when applied incorrectly during development.  It's only a somewhat reasonable choice for a release build. But dead store elimination is the *only* benefit you should take from it, you should still never rely on this as a "feature".

In comparison, MSVC had enabled `/GS` by default for about a decade now, and by personal experience outside the OSS sector, this was one of the worst offenders when it came to masking errors which rendered code unsafe to port to *conforming* compilers. Not just once, but repeatedly. Senior developers who didn't even knew you had to initialize local variables thanks to this "feature" were a real thing.

The bad part starts when QA relies heavily on tooling like valgrind / Intel Inspector to check for uninitialized memory accesses (not everyone is a developer), and these "helpful" compiler options just render you blind to issues you could have seen a long time ago.

The impact is even bigger when this causes errors in pre-built 3rd-party libraries to be masked, which are surprisingly often unmasked by validating an integrating application with real world data, rather than the (unfortunately often insufficient) data the application was tested against.

**Comment by thomasnyman** [comment]
The contraindicators brought up by @Ext3h and @siddhesh seem to substantial enough that I would propose we do not recommend this option in the guide at this point in time, but include it in the [List of Considered Compiler Options](https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++#appendix-list-of-considered-compiler-options) with a brief summary of [Ext3h's comment](https://github.com/ossf/wg-best-practices-os-developers/issues/245#issuecomment-1785479519).

**Comment by SecurityCRob** [comment]
Has this been addressed by the C/C++ Compiler Hardening options guide?    @gkunz @thomasnyman @david-a-wheeler

**Comment by thomasnyman** [comment]
Closing after review in [Compiler BP Call 2024-06-27](https://docs.google.com/document/d/1JY8FREBPCUUFpuv7-4B9EjeS2MLDpel0dbG5DFWrTns/edit#bookmark=id.dhr32hb9yx35).

**Comment by rcseacord** [comment]
I think you added this, but the -ftrivial-auto-var-init=choice only works for GCC.  Clang has the very oddly named  -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang.  I'm trying to determine what's behind this name and if it should be used or not.  I think the compiling hardening guide should definitely address this one way or the other.

**Comment by thesamesam** [comment]
That's not right for latest Clang. I wrote about this somewhere once but the document is correct.

**Comment by thomasnyman** [comment]
Indeed this name change had already happened at the time we included `-ftrivial-auto-var-init`in the guide. 

Thanks @thesamesam again for covering the relevant Clang/LLVM lore! 

I remember the leftover documentation confused me when attributing it to the correct Clang version, but the option was included (with the same option name as in GCC) in the [Clang 8.0.0 release notes](https://releases.llvm.org/8.0.1/tools/clang/docs/ReleaseNotes.html), which is the basis for the Clang version given in the guide.
