### ISSUE TITLE
SECURITY.md

### ISSUE THREAD

**Issue by afmarcum** [ossf/wg-best-practices-os-developers#248]
As part of the ongoing community health check effort, each WG should have a SECURITY.md in place. Currently all WGs do not have one and the first repo found with one was Scorecard. 

Please review and modify the example below to serve as the template for each WG to use or build from as their SECURITY.md. Would a week be long enough to provide input? If so, this can be presented to the TAC at the next meeting on 17Oct2023. Open to other timelines as well. 

[Reporting Security Issues](https://github.com/ossf/scorecard/blob/main/SECURITY.md#reporting-security-issues)
To report a security issue, please email [---] with a description of the issue, the steps you took to create the issue, affected versions, and, if known, mitigations for the issue.

Our vulnerability management team will respond within 3 working days of your email. If the issue is confirmed as a vulnerability, we will open a Security Advisory and acknowledge your contributions as part of it. This project follows a 90 day disclosure timeline.

**Comment by david-a-wheeler** [comment]
Hi - are you sure?

I think we generally do *NOT* want people to report a vulnerability to the WG. All the WG will do is *eventually* pass the report down to the responsible project. That extra step would add unnecessary delay. It would also mean that the project wouldn't (at first) be directly talking with the finders. All bad things.

The [general policy of the LF is to contact the *specific* project in charge of the vulnerable component](https://www.linuxfoundation.org/security). That speeds response.

I walked through all the code repos, and almost all of them already have SECURITY.md files. I think that's the better measure. I didn't check on SECURITY.md files at the working group level, because I thought that's frankly too high a level. 

So: I'm not sure we want *any* WG to have a SECURITY.md file. Are we sure?  I guess they could remind people to report to the specific project, and then *only* report to the WG or OpenSSF if they got no response from the project. That kind of SECURITY.md file would NOT look anything like a "send a message here to get a security response" message. So if you think WGs should have SECURITY.md files, I suggest something like this:

Per the [Linux Foundation Vulnerability Disclosure Policy](https://www.linuxfoundation.org/security), if you find a vulnerability in a project maintained by the OpenSSF, please report that *directly* to the project maintaining that code. If you've been unable to find a way to report it, or have received no response after repeated attempts, please contact the OpenSSF security contact email, security `@` openssf.org. Thank you.

**Comment by lehors** [comment]
I agree with David, under our charter WG are not software focused, projects are. So, on that basis we should rather make sure that all projects have a SECURITY.md file, not WGs.

**Comment by afmarcum** [comment]
Thank you for the feedback. This gets us to where we want to be with consistency across repos. Can we proceed with David's suggestion as a second line of defense at the WG level? Staff will continue the audit and work with individual projects if security.md files are missing.

`
Per the [Linux Foundation Vulnerability Disclosure Policy](https://www.linuxfoundation.org/security), if you find a vulnerability in a project maintained by the OpenSSF, please report that directly to the project maintaining that code. If you've been unable to find a way to report it, or have received no response after repeated attempts, please contact the OpenSSF security contact email, security @ openssf.org. Thank you.`

**Comment by drusso-rh** [comment]
+1 to David's proposal.

**Comment by afmarcum** [comment]
Discussed during Best WG meeting. No opposition to David's recommendation. Shared with WG leads and will update repos this week. WGs have been asked to modify and/or merge the PRs by end of month.
