### ISSUE TITLE
Feedback before initial release of Compiler Options Hardening Guide for C and C++

### ISSUE THREAD

**Issue by thomasnyman** [ossf/wg-best-practices-os-developers#250]
Opening this issue for collecting feedback on the proposed [**Compiler Options Hardening Guide for C and C++**](https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++) before its initial release.

Tagged release candidate for the guide can be found [here](https://github.com/ossf/wg-best-practices-os-developers/blob/compiler-hardening-guide-rc1/docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C%2B%2B.md).

**Comment by tcullum-rh** [comment]
Hi,

This guide is quite comprehensive! My only current suggestion is that as a developer, I would really appreciate more info about this:

> 
Those who build programs for production may choose to omit some options that hurt performance if the program only processes trusted data, but remember that it’s not helpful to deploy programs that that are insecure and rapidly do the wrong thing. Existing programs may need to be modified over time to work with some of these options.

It would be helpful if for each option (or only the relevant options), a statement was made as to what the performance or other drawbacks are and any relevant workarounds.

**Comment by thomasnyman** [comment]
> It would be helpful if for each option (or only the relevant options), a statement was made as to what the performance or other drawbacks are and any relevant workarounds.

Thank you for the feedback @tcullum-rh. 

They way in which we have tried to accommodate this in the current version of the guide are the **Performance implications** and **When not to use?** sections in the detailed descriptions for each option (excluding the Warning options, as they do not impact the produced binary directly).

For example, for [-fstack-protector-strong](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C%2B%2B.md#performance-implications-3):

>
> Stack protector supports three different heuristics that are used to determine which functions are instrumented with run-time checks during compilation:
>
> -fstack-protector-strong: instrument any function that takes the address of any of its local variables on the right-hand-side of an assignment or as part of a function argument allocates a local array, regardless of type or length
allocates a local struct or union which contains an array, regardless of the type of length of the array
has explicit local register variables
> -fstack-protector: instrument functions that call alloca() or allocate character arrays of n bytes or more in size . The threshold for instrumentation is adjustable via the --param=ssp-buffer-size=n option (default: 8 bytes).
>-fstack-protector-all: instrument all functions.
>
> The performance overhead is dependent on the number of function’s instrumented and the frequency at which instrumented functions are activated at run-time. Enabling -fstack-protector-strong is recommended as it provides the best balance between function coverage and performance. Projects using older compiler versions can consider -fstack-protector-all or -fstack-protector with a stricter threshold, e.g. --param=ssp-buffer-size=4.
>
> When not to use?
>
> -fstack-protector-strong is recommended for all applications with conventional stack behavior. Applications with hand-written assembler optimization that make assumptions about the layout of the stack may be incompatible with stack-protector functionality.

In general, the performance impact is surely the most frequently asked question when considering the deployment of these types of compiler options. Sadly, it is very difficult to estimate the impact in general, as it is dependent on the interaction with specific characteristics of the source code. Therefore, we've opted to try and characterize _where_ the overhead comes from to try to help developers with how to measure the overhead in meaningful benchmarks in their project.

We are of course open to other suggestions of what kind of information would be useful for practitioners.

**Comment by david-a-wheeler** [comment]
@tcullum-rh : We agree in *principle* that important issues/caveats with an option should be mentioned with the option. In several cases where the issues are clear we *have* tried to do this. Sadly, often the answer is the lawyer's answer: "It depends". Whether or not there's a nontrivial performance impact often depends on many other factors, in particular, optimizations can sometimes (but not always) reduce or eliminate performance costs. If there's an important case where there's a clear issue and we haven't discussed it, please propose adding it! In *general*, the only way to answer the question is to run benchmarks. Everything else is only a quick estimate of the likely result.

**Comment by david-a-wheeler** [comment]
I created a PR https://github.com/ossf/wg-best-practices-os-developers/pull/259 to briefly discuss system headers.

**Comment by eslerm** [comment]
Thank you for this!

Could you consider adding `-mbranch-protection=standard` for arm64? This is default in [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1021292) and [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1847148). In 2019 using glibc, [Arm measured](https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/code-reuse-attacks-the-compiler-story) the use of the `bti+pac` options to reduce ~98% of ROP and JOP gadgets.

Is `--enable-default-pie` more appropriate?

**Comment by eslerm** [comment]
*For developers*, could we recommend `-fstrict-flex-arrays=3` and `-fsanitize=bounds`.

https://people.kernel.org/kees/bounded-flexible-arrays-in-c
https://www.youtube.com/watch?v=V2kzptQG5_A

Distros need to test these flags and report breaks upstream before they can be a widely used.

**Comment by kees** [comment]
Please also add `-Wimplicit-fallthrough`

**Comment by david-a-wheeler** [comment]
@kees: Thanks so much for your feedback! I think adding `-Wimplicit-fallthrough` is a great idea.

**Comment by david-a-wheeler** [comment]
[eslerm](https://github.com/eslerm) commented [24 minutes ago](https://github.com/ossf/wg-best-practices-os-developers/issues/250#issuecomment-1763121934)

> For developers, could we recommend -fstrict-flex-arrays=3 and -fsanitize=bounds?

FYI, we have a separate issue specifically discussing `-fstrict-flex-arrays` here: https://github.com/ossf/wg-best-practices-os-developers/issues/249

I'm supportive for adding `-fstrict-flex-arrays` but that *does* imply a lot of changes for some programs. Also, last I checked clang didn't support level 3 (which I think is a mistake on their part, but I don't control the clang project :-) ).

I don't think people have seriously considered adding `-fsanitize=bounds`, which instruments array bounds. The problem is the non-trivial performance overhead. The design of C (and thus C++) makes it challenging to have good performance when doing the kind of bounds-checking that is the default in almost all other programming languages. Here's one study, I'm sure there are more: <https://zatoichi-engineer.github.io/2017/10/05/sanitize-object-size.html>. Some people may find the performance loss unacceptable, but C and C++ tend to used in the very situations where performance matters. That isn't necessarily the end of the story, though. The current draft focuses only on option flags for *production* use. There's been discussion about extending this document to also include flags for use during testing and debugging. That *WOULD* make sense there - it makes sense to turn on sanitizers and run dynamic tools like fuzzers and test suites. Maybe you could help us expand the document to those use cases?

**Comment by eslerm** [comment]
Thanks David. Ack on *production* use.

Clang now supports level 3, but only on rather recent versions.

There is a similar ongoing discussion with GCC: [RFC: Introduce -fhardened to enable security-related flags](https://gcc.gnu.org/pipermail/gcc-patches/2023-August/628748.html).

**Comment by kees** [comment]
Clang supports `-fstrict-flex-arrays=3`, so no worries there.

**Comment by david-a-wheeler** [comment]
This article has lots of ideas, I'm not sure we can do them all before an initial release: https://developers.redhat.com/articles/2022/06/02/use-compiler-flags-stack-protection-gcc-and-clang

**Comment by david-a-wheeler** [comment]
Per [eslerm](https://github.com/eslerm) comment (https://github.com/ossf/wg-best-practices-os-developers/issues/250#issuecomment-1762253579) I created a PR proposing to add branch protections here: https://github.com/ossf/wg-best-practices-os-developers/pull/260
This covers `-mbranch-protection=standard` and `-fcf-protection=full`.

**Comment by david-a-wheeler** [comment]
[eslerm](https://github.com/eslerm) commented [4 days ago](https://github.com/ossf/wg-best-practices-os-developers/issues/250#issuecomment-1762253579) asked:
> Is `--enable-default-pie` more appropriate?

Interesting question. First, some context. I believe that [`--enable-default-pie` is a GCC option used when *recompiling* the GCC compiler](https://gcc.gnu.org/install/configure.html). By using it, the generated GCC compiler will default to  including `-fPIE` and `-pie` options by default when it compiles something else. As far as I know that is GCC-specific. I believe a somewhat-equivalent configuration option clang/LLVM world is [CLANG_DEFAULT_PIE_ON_LINUX](https://discourse.llvm.org/t/default-setting-for-clang-default-pie-on-linux/61688). See [this discussion on the clang default setting](https://discourse.llvm.org/t/default-setting-for-clang-default-pie-on-linux/61688).

The problem with these options is that many application developers do *NOT* recompile their own compiler. They instead use a compiler provided to them (e.g., the system compiler or one distributed for their chipset). So while these options are valid if you're recompiling the compiler (e.g., a Linux distro), I think we *cannot* remove `-fPIE` and `-pie` because using them *ensures* you get the safer setting.

We could add a note that "if you recompile the compiler itself, it's best to modify its configuration itself so its defaults are maximally secure for any software compiled using it. For example..." or something along those lines.

**Comment by david-a-wheeler** [comment]
I've created a PR to note that if you *are* compiling a compiler, make its defaults as safe/secure as you can. For many readers this isn't helpful (many developers do *not* compile their own compilers), but this *is* a useful note for Linux distributions and some others who *do* compile their own compilers: https://github.com/ossf/wg-best-practices-os-developers/pull/261

**Comment by david-a-wheeler** [comment]
I've added this PR to add `-Wimplicit-fallthrough`: https://github.com/ossf/wg-best-practices-os-developers/pull/262

**Comment by david-a-wheeler** [comment]
This PR proposes to add the option `-fstrict-flex-arrays=3`: https://github.com/ossf/wg-best-practices-os-developers/pull/263

Note that this PR, if accepted, would fix issue #249.

**Comment by david-a-wheeler** [comment]
I propose that *before* the initial release we merge the PRs in response to this issue. That is, at least accept #259, #260, #261, #262, #263. If there are other PRs that are (mainly) ready to go, let's get them in. I'd like our first draft to have at least the main agreed-on results that I believe are captured here.

**Comment by david-a-wheeler** [comment]
We should probably discuss adding `-mshstk` to the C/C++ Compiler Hardening Guide. I've created a separate issue #267 to track this. Is anyone aware of any *problems* with this flag? If they are, please comment on #267.

**Comment by david-a-wheeler** [comment]
@gkunz  @thomasnyman and others - I'd love to hear your thoughts on https://github.com/ossf/wg-best-practices-os-developers/pull/259, https://github.com/ossf/wg-best-practices-os-developers/pull/260, https://github.com/ossf/wg-best-practices-os-developers/pull/261, https://github.com/ossf/wg-best-practices-os-developers/pull/262, https://github.com/ossf/wg-best-practices-os-developers/pull/263 . If you think they makes sense, please merge (or say it's okay to merge). We might want to implement #267 but I expect we'll create merge conflicts as long as we have a number of changes outstanding. Merge conflicts aren't the end of the world, but I'd rather not need to deal with them unnecessarily :-).

**Comment by thesamesam** [comment]
> _For developers_, could we recommend `-fstrict-flex-arrays=3` and `-fsanitize=bounds`?
> 
> [people.kernel.org/kees/bounded-flexible-arrays-in-c](https://people.kernel.org/kees/bounded-flexible-arrays-in-c) [youtube.com/watch?v=V2kzptQG5_A](https://www.youtube.com/watch?v=V2kzptQG5_A)
> 
> Distros need to test these flags and report breaks upstream before they can be a widely used.

I like the idea of this but this may deserve an "emerging features" section or similar (things we want to work towards). It's not suitable for global use right now, but it'd be great if anyone wants to take up work to get us there. Listing it as a goal would let us list it without giving people the worng idea.

**Comment by Flo4152** [comment]
Two paragraphs in section 3.11.1 have roughly the same meaning.

`Out-of-date versions of GCC may not detect or defend against overflows of dynamically-sized local
variables such as variable-length arrays or buffers allocated using alloca() when compiling for
64-bit Arm (Aarch64) processors. Users of GCC-based toolchains for Aarch64 should ensure they
use up-to-date versions of GCC 7 or later that support an alternative stack frame layout that places
all local variables below saved registers, with the stack-protector canary between them.`

`Some versions of GCC may not detect or defend against overflows of dynamically-sized local
variables such as variable-length arrays or buffers allocated using alloca() when compiling for 64-
bit Arm (Aarch64) processors. Users of GCC-based toolchains for Aarch64 should, before
depending on it, determine if they support an alternative stack frame layout that places all local
variables below saved registers, with the stack-protector canary between them.`

I understand that its deals with with two different things : "Out-of-date versions " and "Some versions" of GCC for aarch64 CPU. But do you think that one paragraph can summarize the two ideas ?

`Out-of-date versions and some versions of GCC may not detect or defend against overflows of dynamically-sized local
variables such as variable-length arrays or buffers allocated using alloca() when compiling for 64-
bit Arm (Aarch64) processors. Users of GCC-based toolchains for Aarch64 should, before
depending on it, determine if they support an alternative stack frame layout that places all local
variables below saved registers, with the stack-protector canary between them.`

**Comment by SecurityCRob** [comment]
We'll close this out as 1.0 is out now!
