### ISSUE TITLE
Compiler Hardening Guide should refer to more compilers based on GCC and clang

### ISSUE THREAD

**Issue by edelsohn** [ossf/wg-best-practices-os-developers#251]
The Compiler Hardening Guide refers to the Intel compiler

```
This document focuses on recommended options for the GNU Compiler Collection (GCC) and clang, and we expect to expand it to cover compilers that have similar option syntax (such as the Intel compiler).
```

The Intel C/C++ Compiler, ARM Compiler, MacOS XCode, and IBM Open XL C/C++ Compiler are based on clang technology.
The Red Hat Developer Toolset, Siemens Sourcery Toolchain, Adacore GNAT Pro are based on GCC technology.

If the guide is going to call out vendor compilers based on GCC and LLVM, it shouldn't only publicize Intel.

**Comment by thomasnyman** [comment]
I believe this wording came about since the Intel representative who participates in the regular calls expressed the intent by their compiler experts to vet the guide for compatibility with the Intel compiler and provide additional guidance specific to that compiler.

There's similar intent expressed by Microsoft for their compiler tracked in issue #150.

It would of course be great to have input from other vendors as well incorporated to the guide and we'd be very happy to receive such contributions.

We should, however, communicate the planned roadmap for the Compiler Hardening Guide more clearly so it becomes clear this is a planned roadmap item and not an arbitrary example. I'll make a note to address this is in upcoming updates to the README file.

**Comment by thomasnyman** [comment]
Thanks for the clarification. If I understood correctly, you are concerned with communicating the _applicability_ of the guide to other compilers, whereas the current text is about the _expections_ for future content.

Perhaps something like: 
> This document focuses on recommended options for the GNU Compiler Collection (GCC) and Clang/LLVM, and we expect to the recommendations to be applicably to other compilers based on GCC and Clang technology, such as the Intel C/C++ Compiler, the Arm Compiler for Embedded, the Apple Clang compiler included in Xcode, IBM Open XL C/C++ Compiler, the Red Hat Developer Toolset, the Siemens Sourcery Toolchain, and AdaCore GNAT. 
> In the future, we aim to expand to guide to also cover other compilers, such as Microsoft MSVC.

**Comment by edelsohn** [comment]
Yes, exactly. I think that it's helpful to mention that the current guide is relevant to all GCC-based and LLVM-based vendor compilers, not just Intel.  Thanks for the proposed text.

**Comment by siddhesh** [comment]
Would it make sense to, instead, not mention any vendor compilers at all?  It seems like we'll always miss some.  Why not simply state:

> This document focuses on recommended options for the GNU Compiler Collection (GCC) and Clang/LLVM, and we expect the recommendations to be applicable to other compilers based on GCC and Clang technology, 

and leave it at that?

**Comment by edelsohn** [comment]
The comment says "such as". It's not intended to be a complete enumeration.  I don't believe that all readers know what compilers based on GCC or Clang technology means.  And some vendors would appreciate the publicity.  It might encourage wider dissemination of the document.

**Comment by siddhesh** [comment]
Fair point; FWIW, it's not a hard objection.  I'm only concerned about having to gate this list (or making a section out of it)  at some point in the future because more vendors reach out, asking their toolchain product(s) to be listed here.

**Comment by david-a-wheeler** [comment]
One alternative is to give the "general" text above, and add a footnote with the list of examples. The footnote means that people can find out about common cases, but it's so hidden that it's clearly not helpful to be included in the list for marketing purposes. We *do* want to help developers; I think giving common examples can be helpful. I'm also sensitive that we don't want to give any particular vendor an advantage or disadvantage just by listing them here. Maybe this would be a helpful compromise?

**Comment by gkunz** [comment]
That's a good compromise because I believe that there is value in listing examples. By explicitly separating those from the text itself, it is clear enough that those are examples and not meant to be a complete list (and then I hope that we don't have to curate requests for including more examples).

**Comment by SecurityCRob** [comment]
+1 on using x86

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security
