### ISSUE TITLE
CodeQL in SKF

### ISSUE THREAD

**Issue by xcorail** [ossf/wg-best-practices-os-developers#28]
## Description
Include CodeQL labs and queries into SKF

## Discussion minutes
- Specific python CodeQL examples for the level 1 ASVS Design patterns
	— http://localhost:4200/projects/manage
	— http://localhost:4200/projects/view/1
	— Per security requirement an CodeQL Python example how to very that requirement
	— If not codeQL query existing then link the generic codeql item
	— The MD files /skf-flask/skf/markdown/code_examlples/web/testing/
	— markdown filename convention example 11-code_example--codeQL_2_1_1.md    (the 2_1_1 is the security requirement identifier) 

- 
- Check with the LGTM if we can reuse their web query editor and completion
	— https://github.com/blabla1337/skf-labs/issues/97
	— Maybe we can use the standalone version?

**Comment by xcorail** [comment]
@blabla1337 @RiieCco can you please give one example of security requirement that had a SEMGREP test correlated? 
I am on the dev branch, everything is in there, right?

**Comment by xcorail** [comment]
Hey @blabla1337 @RiieCco trying to revive or kill this old issue.
From memory, 
* We didn't move on adding CodeQL as Labs: The CodeQL team didn't have the capacity to work in parallel on replacing LGTM.com natively on GitHub (FYI, LGTM.com will be deprecated end of year) and on implementing a solution in SKF.
* We made an attempt of adding a CodeQL query as an example of a specification, as it was already the case with SEMGREP. I honestly don't remember where we left this off 😞 

Do you think there is value in reviving / rediscussing this issue, or should we close it for now?

**Comment by RiieCco** [comment]
Hey @xcorail,

Long time no talk man, I hope all is well on your side! :-D
I think we can still try to make this work.

So, since we now have the Apache guacamole box I was also considering
creating machines with a vuln app in it "forked from a vuln repo in the past with some interesting vulns"

I want to use that environment to teach people how to do secure code reviews.
Teach them the proper methodology, and approach and provide them with tools they can use.

So it could be something like:

> use Sonarqube to detect cyclomatic complexity.
> use CodeQL to detect dangerous sinks
> use defect dojo for vulnerability management

Since we don't have to use "isolated" patterns of CodeQL we can just include the runner in the guacamole box
and let it run full blast right? I think when scoping the usage of CodeQL like that it becomes more 
feasible for implementation right?

What you think? ^^

**Comment by xcorail** [comment]
I love it
In particular 'use CodeQL to detect dangerous sinks` will teach people how they can use it to **augment** their audits with this fast exploration feature, rather than just launch it to find a vulnerability.
Let's discuss further!

**Comment by ran-dall** [comment]
Tagging @aFuzzyBear who has ideas about this as well.

**Comment by SecurityCRob** [comment]
Been over 1.5 yrs since last update.  Closing, can re-open if folks rediscover interest in moving this forwad
