### ISSUE TITLE
Proposal: workflow view of scorecard and badge output

### ISSUE THREAD

**Issue by lucasgonze** [ossf/wg-best-practices-os-developers#344]
# Summary

The Scorecard and Best Practices Badge should be available in a format conducive to program management, such as a TSV of issues or a kanban of cards.

# Problem

The Scorecard and Best Practices Badge are useful for organizing security tasks. A team can research what needs to be done by running the tool, then turn each open item into a ticket. However, their output is incompatible with program management tooling and methodologies.

# Solution

- Identify target tooling and methodologies, such as Github Issues and Kanban.
- Format program output in a way that is easy to channel into the target tooling and methodologies

# Context

[Proposed Initiative: "Maintainer Experience"](https://github.com/ossf/tac/issues/169):

> We need to meet maintainers where they are in order to raise awareness of OpenSSF.
> We need to ensure they achieve this understanding in as little time as possible.
> We need to present the activities of OpenSSF in a pain point/solution-focused way, to help make our benefits tangible and demonstrate empathy with their needs.

A comment by @lucasgonze:

> What is very useful is guiding my roadmap as a security TPM for FOSS projects. I treat the criteria as checklists. By running the metrics I figure out what I do and don't need to work on. For example, this month I am cleaning up CodeQL alerts as a result of working through https://bestpractices.coreinfrastructure.org/en/projects/6358#analysis and getting a failing score on the static_analysis_fixed metric.
>
> What I would want from the WGs is to reframe their outputs as a guide for security-related workflows. For example there could be a Kanban template with the first swim lane prefilled with cards corresponding to metrics. I have [something similar for OpenChain](https://github.com/users/lucasgonze/projects/5/views/1), which has a comparable role for getting an OSPO organized.

A comment by @SecurityCRob:

>  I'll put this on the docket for the group to discuss in Jan2024. We certainly can spin up a group to work on crafting a checklist/guide to deliver something as you suggest.
> 
> In the meantime, the group would welcome your feedback in a future WG meeting or perhaps *an issue* describing your desired artifact that we could collaborate on together: https://github.com/ossf/wg-best-practices-os-developers/issues

This ticket is provided as the issue describing the desired artifact to collaborate on.

**Comment by lucasgonze** [comment]
@SecurityCRob Would it work to put this on the agenda for the January 8 Scorecards/AllStar bi-weekly sync meeting?
![image](https://github.com/ossf/wg-best-practices-os-developers/assets/111581/cb144bbb-1e78-43a3-ba9a-191acfd1814d)

**Comment by lucasgonze** [comment]
Notes from Jan 8 2024 meeting:
* Usability review of "hide completed" toggle in Best Practice UI

**Comment by david-a-wheeler** [comment]
Lucas will add an issue specific to scorecard, and close out this PR.

**Comment by david-a-wheeler** [comment]
In the best practices badge project, the current *plan* is to improve visibility of the functionality that shows "what is left to do". This functionality *already* exists, but it appears it's not obvious enough, so some UI tweaks seem warranted. See: <https://github.com/coreinfrastructure/best-practices-badge/issues/2093>

I think it's very reasonable to add the ability to generate Markdown "todo" list for GitHub/GitLab issues, Kanban boards, etc. That's because many tools (including GitHub, GitLab, and so on) can directly import markdown. No commitment yet, but certainly plausible. See: <https://github.com/coreinfrastructure/best-practices-badge/issues/2094>.

It's obviously possible to generate CSV, etc. However, the BP badge already generates JSON; CSV doesn't change much, since you'd *still* need to write software to extract the JSON or CSV to turn it into something people are likely to use. So I'm sympathetic, but we need to find some people who would commit to using this added format & how. Otherwise, we're just writing code no one will use.

**Comment by lucasgonze** [comment]
I added a comment to https://github.com/coreinfrastructure/best-practices-badge/issues/2093 to call out the potential for adding markdown. Given that, we have addressed all three followups we identified in today's meeting. Fixes can proceed in these new issues for the scorecard and badge.

**Comment by david-a-wheeler** [comment]
FYI, the best practices badge now has a "secret" way to generate a todo list in GitHub flavored markdown. Just add a ".md" extension to the project entry. If people like it, we can reveal it.

URL Examples:

*   https://www.bestpractices.dev/en/projects/1.md for the passing criteria for project 1 in English
*   https://www.bestpractices.dev/en/projects/1.md?criteria_level=1 for silver
  *   https://www.bestpractices.dev/en/projects/1.md?criteria_level=2 for gold
* https://www.bestpractices.dev/fr/projects/1.md for French (you can use any supported locale; if the locale is omitted, it redirects to the user's preferred locale)
