### ISSUE TITLE
This would make a great blog post!

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-best-practices-os-developers#71]
As we near publication of our two "quick guides" we need to craft a blog to be published via an OSSF blog for the following gdocs:

One page guide for developing secure software - https://docs.google.com/document/d/16jUqTEFG-wscZUGR-NGa_3a81GF3YILtH9XgOSkLCTM/edit#

Concise Guide for evaluating OSS - https://docs.google.com/document/d/19015o63pA-sZPBN5-R7I7Cg8ICPxo6fXH8vOI1RgBYM/edit#

**Comment by ran-dall** [comment]
@SecurityCRob I can start a draft of blog post and then send it out later on a Google Docs link to mailing list if you'd like.

**Comment by SecurityCRob** [comment]
Please!!

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security

**Comment by david-a-wheeler** [comment]
FYI, they are now the "concise" guides (due to a title rename).

More importantly, the Google docs versions are now obsolete. We've now converted them to markdown on GitHub, so we can carefully control future changes. Google docs is great for quick group edits, but we're now past that point.

The final-draft markdown versions are here:
* ["Concise Guide for Developing More Secure Software"](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Concise-Guide-for-Developing-More-Secure-Software.md)
* ["Concise Guide for Evaluating Open Source Software"](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Concise-Guide-for-Evaluating-Open-Source-Software.md)

**Comment by torgo** [comment]
This was completed: https://openssf.org/blog/2022/09/13/introducing-new-concise-guides-for-developing-more-secure-software-and-evaluating-open-source-software/
